
version: "3.3"

services:
  jupyter:
    build:
      context: .
    ports:
      - "8888:8888"

    # dockertoolbox only mount c:/Users
    # so many hours wasted Jesus.
    # https://github.com/docker/kitematic/issues/2738
    volumes:
        - C:\Users\baram204\dev\goStudy\study:/study

#    volumes:
#      - type: "bind"
#        source: ./../../examples
#        target: /examples
